### ISSUE TITLE
Include Trivy  "contrib" Templates in Image

### ISSUE THREAD

**Issue by miralgj** [bitnami/bitnami-docker-trivy#4]
### Name and Version

bitnami/trivy:0.23.0

### What is the problem this feature will solve?

Typically this image is used as part of a CI pipeline to scan images as they are being built. Trivy includes a few templates for reporting that are useful to produce as downloadable artifacts for your pipelines.

### What is the feature you are proposing to solve the problem?

Include Trivy's `contrib/*.tpl` files in the image.

### What alternatives have you considered?

Downloading the desired template as a step in your CI pipeline. While this works, it would be nice to avoid downloading the template each time or having to include it in your project.

**Comment by juan131** [comment]
Hi @miralgj 

Thanks for this feature request! I've been checking it with the team and we also think it's something we should include in the image. I'll open a internal task to include it in future releases.

**Comment by Mauraza** [comment]
Hi @miralgj,

We just include 'contrib' in the last version '0.27.1-debian-10-r2'. Could you check it?

**Comment by miralgj** [comment]
Looks good. Thank you!
