### ISSUE TITLE
Problem while trying to put the DB file in Trivy's cache directory (Air-gaped environment)

### ISSUE THREAD

**Issue by crytech7** [bitnami/bitnami-docker-trivy#5]
### Name and Version

bitnami/trivy:0.22.0-debian-10-r7

### What steps will reproduce the bug?

1. After running Trivy (`docker run -t -d --name trivy bitnami/trivy:0.22.0-debian-10-r7`)
2. I was trying to use `docker exec -it <container name> /bin/bash` command to get a bash shell in the container. The purpose was to configure Trivy in the running container to be used in air-gapped environment by following the official guidlines ( https://aquasecurity.github.io/trivy/v0.17.0/air-gap/ ). 
3. Then an error occured: `Error response from daemon: Container 8e077c177ef31319fed9158802d3569bc9613f529780a0314e2ccbb4d00e0b8e is not running`

### What is the expected behavior?

Could you please advice me how to solve this problem and correctly put the DB file in Trivy's cache directory inside the docker container?

Yours faithfully,
Tiana

### What do you see instead?

![image](https://user-images.githubusercontent.com/75042095/172150435-c116f929-cf51-4ddb-8ce2-902d440f2815.png)

The additional flags `-t -d` did not help, container exits after  run

**Comment by rafariossaa** [comment]
Hi,
  Could you provide the logs for the container ?
